# clowder server
clowder:
  image: clowder/clowder:1.1.1
  ports:
    - "9000:9000"
  links:
    - mongo
    - rabbitmq

# mongo database used to store metadata/data
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"

# rabbitmq to connect to extractors
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"